# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
AllCops:
  NewCops: enable
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  SafeAutoCorrect: true
Layout/LineLength:
  AutoCorrect: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 80
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/ClassAndModuleChildren:
  Enabled: false
Style/ExtraSpacing:
  ForceEqualSignAlignment: true

Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
