AllCops:
  Exclude:
    - 'lib/moleculer/serializers/protobuf/packets/packets.pb.rb'

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  IgnoredPatterns: []

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/ModuleFunction:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
    EnforcedStyle: "double_quotes"

Metrics/LineLength:
  Max: 120
  IgnoreCopDirectives: true

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

